pub mod request;
pub mod response;
pub mod router;
pub mod server;
pub mod middleware;
pub use middleware::CorsMiddleware;
pub mod error;
pub use really_fast_api_macros::{get, post, put, delete};
pub use request::Req;
pub use response::{Res, StatusCode};
pub use router::App;